name: CI Demo Web

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: webbutvecklinghelsingborg/gitops:latest,webbutvecklinghelsingborg/gitops:${{ github.sha }}

      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: yo-l1982
          repo: demo-web-config
          github_token: ${{ secrets.DEMO_WEB_GH_TOKEN }}
          workflow_file_name: demo-web-deploy.yaml
          inputs: '{sha: "${{ github.sha }}"}'
          wait_workflow: false

